# Generated by Django 4.2.19 on 2025-03-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('IN_ACTIVE', 'In Active'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='IN_ACTIVE', max_length=12),
        ),
    ]
