# Generated by Django 4.2.19 on 2025-03-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_recurring',
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_reocurring',
            field=models.BooleanField(default=False),
        ),
    ]
