# Generated by Django 4.2.19 on 2025-03-02 23:33

import business.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='plan',
            field=models.ForeignKey(default=business.models.get_default_plan, on_delete=django.db.models.deletion.SET_DEFAULT, to='plan.plan'),
        ),
    ]
