# Generated by Django 4.2.19 on 2025-03-05 13:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_name_alter_permission_name'),
        ('business', '0003_otp_alter_business_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(6)])),
                ('address', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('modules', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.module')),
            ],
        ),
    ]
