# Generated by Django 4.2.19 on 2025-03-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_name_alter_permission_name'),
        ('business', '0004_alter_business_phone_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='modules',
        ),
        migrations.AddField(
            model_name='employee',
            name='modules',
            field=models.ManyToManyField(related_name='employees', to='modules.module'),
        ),
    ]
