# Generated by Django 4.2.19 on 2025-03-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_remove_employee_modules_employee_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='change_password',
            field=models.BooleanField(default=False),
        ),
    ]
