# Generated by Django 4.2.19 on 2025-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='modules',
            field=models.JSONField(default=list),
        ),
    ]
