# Generated by Django 4.2.19 on 2025-03-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_name_alter_permission_name'),
        ('plan', '0002_plan_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='modules',
        ),
        migrations.AddField(
            model_name='plan',
            name='modules',
            field=models.ManyToManyField(related_name='plans', to='modules.module'),
        ),
    ]
